version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    image: osimis/orthanc
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - "/Users/theophilushomawoo/Documents/stage/galeo/python/OrthancGif:/python/:ro"
    volumes: [ "dicom_storage:/var/lib/orthanc/db:Z" ]
    ports:
      - 4242:4242
      - 8042:8042
    environment:
       ORTHANC__NAME: "orthanc"
       VERBOSE_ENABLED: "true"
       #VERBOSE_STARTUP: "true"
       PYTHON_PLUGIN_ENABLED: "true"
       ORTHANC__PYTHON_VERBOSE: "true"
       ORTHANC__PYTHON_SCRIPT: "/python/index.py"
       NEURO_PLUGIN_ENABLED: "true"

volumes:
  dicom_storage: